import type { Metadata } from "next";

import { CopilotKit } from "@copilotkit/react-core";
import { URLParamsProvider } from "@/contexts/url-params-context";
import "./globals.css";
import "@copilotkit/react-ui/styles.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"antialiased"}>
        <URLParamsProvider>
          {children}
        </URLParamsProvider>
      </body>
    </html>
  );
}
